name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: severikupari1/vue-amb-typescript
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build 
        BUILD_DIR: dist/
