name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: severikupari1/vue-amb-typescript
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build && yarn storybook:build
        BUILD_DIR: blog/.vuepress/dist/
